"""empty message

Revision ID: 063cdc9baff6
Revises: c1de0f37f7c4
Create Date: 2020-10-05 18:05:20.865267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063cdc9baff6'
down_revision = 'c1de0f37f7c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###
