"""Create ltree extention

Revision ID: 1e257c951944
Revises: b7a58d426793
Create Date: 2020-10-23 12:09:29.219665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e257c951944'
down_revision = 'b7a58d426793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("CREATE EXTENSION IF NOT EXISTS ltree;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("DROP EXTENSION IF EXISTS ltree;")
    # ### end Alembic commands ###
