"""add user following

Revision ID: d3ac8ef89d39
Revises: 11380372186a
Create Date: 2020-10-15 15:12:55.221153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ac8ef89d39'
down_revision = '11380372186a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('follower_id', sa.String(), nullable=True),
    sa.Column('followee_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
